### ISSUE TITLE
Build error error: cannot find symbol EntryConverter

### ISSUE THREAD

**Issue by gustavo84** [Kyald1412/CoronaVirus-2019-nCoV-Live-Tracking#1]
\AppDatabase.java:5: error: cannot find symbol
@androidx.room.TypeConverters(value = {EntryConverter.class})
                                       ^
  symbol: class EntryConverter

**Comment by Kyald1412** [comment]
Resolved 8bb3a764009dc4f970092950a5337dd784459023
