### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by nitanmarcel** [Kyald1412/CoronaVirus-2019-nCoV-Live-Tracking#2]
Hi! I have a simple API suggestion that so far has exact data about the covid-19 status worldwide.

https://github.com/novelcovid/api

**Comment by Kyald1412** [comment]
Hi, i will add more datasources progressively, thank your for your suggestion!

**Comment by Kyald1412** [comment]
Updated! ec47a0c511efe077e97251b412b0ccf4888e1a04
