### ISSUE TITLE
Lags after opened

### ISSUE THREAD

**Issue by sunmughan** [Kyald1412/CoronaVirus-2019-nCoV-Live-Tracking#3]
App works fine on first open after installation. But when we reopen it, it lags and don't don anything. Sometimes work really slowly.

**Comment by Kyald1412** [comment]
Thank you for reaching out!
I'm gonna check it.

**Comment by Kyald1412** [comment]
Improved on dd3489cc79ce3d76cc26cdaece7b0e985e518813
Please check new version, thanks!
