### ISSUE TITLE
App crashes constantly

### ISSUE THREAD

**Issue by sleepercode** [Kyald1412/CoronaVirus-2019-nCoV-Live-Tracking#5]
The app crashes when it's launched.
Error code:

java.lang.NumberFormatException: empty String at sun.misc.FloatingDecimal.readJavaFormatString(Floating ecimal.java:1842) at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.ja va:110) at java.lang.Double.parseDouble(Double.java:538) at co.kyald.coronavirustracking.b.b.b$b$a.b(:116) at co.kyald.coronavirustracking.b.b.b$b$a.a(Unknown Source:10) at kotlinx.coroutines.j2.b.a(:91) at kotlinx.coroutines.e.a(:154) at kotlinx.coroutines.d.a(:1) at co.kyald.coronavirustracking.b.b.b$b.b(:102) at co.kyald.coronavirustracking.b.b.b$b.a(Unknown Source:10) at kotlinx.coroutines.j2.b.a(:91) at kotlinx.coroutines.e.a(:154) at kotlinx.coroutines.d.a(:1) at co.kyald.coronavirustracking.b.b.b.a(:96) at co.kyald.coronavirustracking.b.b.b$c$a.b(:59) at e.eo.i.a.a.a(:33) at kotlinx.coroutines.po.run(:56) at kotlinx.coroutines.k2.a.a(:561) at kotlinx.coroutines.k2.a$b.a(:727) at kotlinx.coroutines.k2.aşb.f(:667) at kotlinx.coroutines.k2.a$b.run(655)

**Comment by Kyald1412** [comment]
Hi, thank you for reaching out!

Already fixed in 2b24145b96e96602fd5065102cd11a4b4b3fb1b9
Please kindly check the newer version!
